---
name: Updatecli

on:
  # Manually trigger Updatecli via GitHub UI
  workflow_dispatch:
  # Trigger Updatecli once day by a cronjob
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run once a day
    - cron: '0 0 * * *'

permissions:
  contents: "write"
  pull-requests: "write"

jobs:
  crates_io_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Install Updatecli in the runner
        uses: updatecli/updatecli-action@v2

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Update and push the changes
        id: push
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          GITHUB_USER: "github-action"
        run: |
          git config --local user.email "49699333+dependabot[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          before=`just current-version ".fleet_api.tag"`
          just generate-and-commit
          after=`just current-version ".fleet_api.tag"`
          if [[ "${before}" != "${after}" ]]; then
            echo publish=true >> $GITHUB_OUTPUT
            git push
          fi

      - uses: dtolnay/rust-toolchain@stable
        if: steps.push.outputs.publish == 'true'

      - name: cargo login
        if: steps.push.outputs.publish == 'true'
        run: cargo login ${{ secrets.CRATES_IO_API_TOKEN }}

      - name: cargo publish
        if: steps.push.outputs.publish == 'true'
        run: cargo publish --all-features
